language: python
sudo: required
dist: trusty

python:
- 2.7

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq vlan

install:
- sudo util/install.sh -Wlnfvw6
- sudo fuser -k 6653/tcp || true

script:
- sudo mn --wifi --test pingall
- sudo python mn_wifi/test/runner.py -v -quick
#- sudo python examples/test/runner.py -v -quick

notifications:
  email:
    on_success: never
# More details: https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
